- .drone.yml
- README.md
- pkgr.yml
Update various spots to account for bbr 1.7.0 (the minimum requirement for bbr.bayes) now being on MPN (as of 2023-05-14 snapshot).
---
I'm marking this as a draft until https://github-drone.metrumrg.com/ is operational again (hook is broken due to stale SSL certs).
> updates for bbr 1.7.0 now being on MPN

- DESCRIPTION
- NEWS.md
This is a small release to get out the Stan-related changes from gh-92 without waiting for the nmbayes-related work that's landing in `main` to be ready for release.
There are a few other changes, but none of them are user-facing code changes.
changeset: https://github.com/metrumresearchgroup/bbr.bayes/compare/0.1.0...release/0.1.1
> Prepare for 0.1.1 release

- .drone.yml
- README.md
- pkgr.yml
This series updates various bits now that bbr.bayes and nmrec are on MPN.  Variants of the drone and pkgr.yml changes are present in #75, but 1) it's not good for these to be held up by that PR and 2) the plan is to replace that PR with a fresh series.
> Updates for MPN additions

- tests/testthat/test-shrinkage.R
Use local_test_dir() so that the temporary directory path is normalized, avoiding the issues described at 13c2053 (tests: add local_tempdir() wrapper that returns normalized paths, 2023-01-16).
---
This is a small fix that was included in gh-75.  I'm extracting it to a dedicated PR because it's not directly related to those changes and there's no reason for it to be held up by that PR.  And the plan is to replace gh-75 with a rerolled series, so now is a good time to do it.
> test-shrinkage: use local_test_dir helper

- R/nmbayes-helpers.R
- R/shrinkage.R
- tests/testthat/test-shrinkage.R
As described in the final commit here, we rely on fread's header detection.  A while ago @timwaterhouse noted that he's hit into issues with the auto-detection on NONMEM files, so it's best to explicitly specify skip.   We made those changes, but they were locked up in gh-75.  The fread changes are not tied to that PR, so this series extracts them to get them into the main line sooner.  (And now's a good time to do so because the plan is to replace gh-75 with a rerolled series.)
This change broke a shrinkage test case because it was relying on fread's auto-detection; the first two commits deal with that.
> nmbayes: don't rely on fread header detection

- .drone.yml
- tests/testthat/test-copy-model-from.R
copy_model_as_nmbayes() calls bbr::copy_model_from() underneath. copy_model_from() is supposed to overwrite the $PROBLEM record for the copied model, but it only handled upper cases record names until bbr's 13fb8e5f (copy_control_stream: use nmrec instead of regex, 2023-07-21).
A copy_model_as_nmbayes() test checks for lines that it expects to be in the parent model but not the new one.  It uses "$prob" for the record name, and expects the old bbr behavior (i.e. the same problem line is in both the parent and child), leading to a failure with the unreleased bbr.
Use an upper case $PROB in the parent model so that copy_model_from() updates the record for bbr's versions before and after 13fb8e5f.
Re: https://github.com/metrumresearchgroup/bbr/pull/604
---
**bbr.bayes main, bbr 1.7.0**
```
$ …
```
> test-copy-model-from.R: adjust check for bbr change

- R/nm-join-bayes.R
The data passed to mrgsolve::data_set() includes post-hoc ETA values from the table.  Drop those so that the ETAs are simulated within the model, as intended.
Thanks to @timwaterhouse for catching this.
Closes #115.
> nm_join_bayes: drop post-hoc ETAs when simulating EPRED

- R/nm-join-bayes.R
This PR purges ETAs from the `data` set prior to simulating in `sim_ipred()`; a similar step was taken in `sim_epred()`. 
@kyleam I'd like to merge this into `main` to get it in place. I wonder if this is confusing some of the investigation around the `etasrc` discrepancy.
Possible that we eventually want to do this earlier on in the function.
> Drop post-hoc etas from data set

- R/nm-join-bayes.R
This just clarifies a comment that was added in #120.
> nm_join_bayes: fix / clarify comment when dropping ETAs from data

- DESCRIPTION
- R/nm-join-bayes.R
- inst/model/mrgsolve/1100.mod
For discussion: 
- We need mrgsolve 1.0.8 or greater
- Passing `etasrc = "data.all"` will tell mrgsolve to get ETAs from the data set; it will generate an error if it doesn't find all of them
- Drop `ETAn` parameters from the example model
Considerations:
- I'm not sure what else might need to change / update. 
- Still testing this ... I think we can compare output from the previous configuration and make sure it is identical to the update?
- Should we wrap the `mrgsim_df()` call in `sim_pred()` in `tryCatch()` in case it errors?
> Use etasrc argument to fix etas in sim_ipred

- R/submit-model.R
- man/stan_submit_model.Rd
- tests/testthat/test-submit-model.R
In a8e18fa (submit_model.bbi_stan_model: drop unsupported args, 2023-01-16), I dropped .bbi_args from the submit_model() method for Stan models.  Under newer versions of R, the check rightly flags this:
checking S3 generic/method consistency ... WARNING
[...]
submit_model:
function(.mod, .bbi_args, .mode, ..., .overwrite, .config_path,
.wait, .dry_run)
submit_model.bbi_stan_model:
function(.mod, .mode, ..., .overwrite)
Add back .bbi_args so that the meaning of the second positional argument is consistent between the generic and Stan submit_model() methods.
Note that this _could_ break some existing callers that pass `.mode` as a positional argument, but it's very unlikely that anyone is doing that given 1) the early stage of this package and 2) that Stan models do not currently support …
> stan submit_model: add .bbi_args for generic/method consistency

- README.md
- vignettes/getting-started-nmbayes.Rmd
- vignettes/getting-started-stan.Rmd
Here's an initial draft of the getting started vignette for nmbayes. 
Unlike our Stan vignette, this is assuming a bit more familiarity with bbr.  It could be fleshed out more, especially compared to the getting started vignettes for bbr and bbr.bayes Stan, but I'm hoping it highlights most of the key differences between nonmem and nmbayes model types.
@seth127 Please feel free to push any edits directly, if you prefer.
> add nmbayes getting started vignette

- .drone.yml
- DESCRIPTION
- NEWS.md
- R/nm-join-bayes.R
- README.md
- _pkgdown.yml
In addition to the normal release bits, this PR
* bumps bbr dependency to latest release
* updates the pkgdown config
* updates a few docs to reflect the new nmbayes support
changeset: <https://github.com/metrumresearchgroup/bbr.bayes/compare/0.1.1...release/0.2.0>
<details>
<summary>mpn.scorecard scores</summary>
```json
{
"testing": {
"check": 0.9,
"covr": 0.9287
},
"documentation": {
"has_vignettes": 1,
"has_website": 1,
"has_news": 1
},
"maintenance": {
"has_maintainer": 1,
"news_current": 1
},
"transparency": {
"has_source_control": 1,
"has_bug_reports_url": 1
}
}
```
```
$ git rev-parse HEAD^{tree}
8f994d98bde27bf8ba72b65a913a667426daf3d8
```
</details>
> Prepare 0.2.0 release

- R/get-path-from-object.R
In bbr 1.10.0, the .mod argument of get_data_path() was renamed to .bbi_object.  The argument in the get_data_path.bbi_nmbayes_model() method should have been renamed too for consistency.
This is flagged under newer versions of R:
checking S3 generic/method consistency ... WARNING
get_data_path:
function(.bbi_object, .check_exists, ...)
get_data_path.bbi_nmbayes_model:
function(.mod, ...)
> nmbayes get_data_path: rename arg to match generic

- R/check-nonmem-finished.R
- man/nmbayes_check_nonmem_finished.Rd
- tests/testthat/test-check-nonmem-finished.R
* update test setup for `check_nonmem_finished` now using the existence of `bbi_config.json`, rather than "Stop Time" in the lst file, as the indicator that a NONMEM model is finished 
* follow bbr's change in behavior for the "missing output directory" case
> nmbayes: check_nonmem_finished updates for upcoming bbr

- R/nmbayes-helpers.R
- man/chain_paths.Rd
Escape braces so that this is rendered as "{id}-{chain}", as intended, not "id-chain".
Closes #149.
> chain_paths: escape braces in docs

- R/get-path-from-object.R
- tests/testthat/test-get-path-from-object.R
As of bbr.bayes 0.2.0, we require at least bbr 1.10.0.  `get_data_path.bbi_nmbayes_model()` should have been updated to match changes to bbr's `get_data_path`:
* fall back to data path from control stream if `bbi_config.json` doesn't exist
* account for new `.check_exists` argument
This PR makes those updates.
> nmbayes: align get_data_path handling with bbr >= 1.10.0

- .github/workflows/main.yaml
- DESCRIPTION
- NEWS.md
In addition to the normal release bits, this PR updates the GitHub Actions R versions to include the R versions from the latest Metworx AMI, dropping the 4.1 job but keeping the 4.0 one.
changeset: <https://github.com/metrumresearchgroup/bbr.bayes/compare/0.2.0...release/0.2.1>
> Prepare 0.2.1 release

- .github/workflows/main.yaml
- R/install_torsten.R
- tests/testthat/helper-test-dir.R
- tests/testthat/test-install-torsten.R
This PR originally started out as an update to the `local_stan_bern_mode` to make it compatible with a change in testthat v3.2.2.  However, the CI was failing for a couple of other reasons:
* dependency updates that are incompatible with the R 4.0 check
* the Torsten **v0.89.1** installation fails on Ubuntu 24.04.
Updating to v0.91.0 resolves that failure, but doing that revealed an issue with `install_torsten`s version selection.
So this PR has turned into a more general "get the CI green" PR.
> Resolve CI failures related to external updates

- DESCRIPTION
- R/submit-model.R
- man/nmbayes_check_nonmem_finished.Rd
- man/nmbayes_submit_model.Rd
- man/stan_submit_model.Rd
In https://github.com/metrumresearchgroup/bbr/pull/692 ([de1a73f9](https://github.com/metrumresearchgroup/bbr/commit/de1a73f9cb4007ea9fa041849092799f9b03e979)), @seth127 pointed out that the `.overwrite` behavior for the nmbayes `submit_model`method  was undocumented.  This PR addresses that by adding a custom `.overwrite` description for `submit_model.bbi_nmbayes_model` method rather than inheriting the `.overwrite` description from `bbr::submit_model`.
The same fix is also made for the `stan` method, and the default value of both methods is switched from `NULL` to `FALSE` to more clearly communicate the default behavior.
---
> submit_model: Fix .overwrite documentation

- R/submit-model.R
- tests/testthat/test-workflow-nmbayes.R
submit_model.bbi_nmbayes_model does an upfront submission of a model to generate the init.chn file that's used as input for the main sampling models.
The caller-specified .wait value is propagated to the initial model submission.  This creates a race between init.chn being created and the main sampling runs reading it in.
Do the initial submission under .wait=TRUE.
Fixes #155
---
cc: @curtisKJ @timwaterhouse
> nmbayes submit_model: ensure inits are generated synchronously

- R/nmbayes-helpers.R
- tests/testthat/test-nmbayes-draws.R
- tests/testthat/test-nmbayes-helpers.R
This PR fixes the `nmbayes_draws` bug that @timwaterhouse reported in gh-156.
It applies the same change from the [suggested workaround](https://github.com/metrumresearchgroup/bbr.bayes/issues/156#issuecomment-2594065245).
The second commit is the main one of interest.  The first one is cosmetic cleanup, and the second one adds an a test that checks that the iph handling (which has distinct logic from this bug) handles ETA names with multiple digits.
---
> nmbayes_draws: fix handling of THETAs with multiple digits

- DESCRIPTION
- NEWS.md
changeset: <https://github.com/metrumresearchgroup/bbr.bayes/compare/0.2.1...release/0.2.2>
<details>
<summary>scores</summary>
```
$ git rev-parse HEAD
eea3539c0e2eedf3a6fb14c2bf7f9350b7ebab39
```
```json
{
"testing": {
"check": 0.9,
"coverage": 0.9292
},
"documentation": {
"has_vignettes": 1,
"has_website": 1,
"has_news": 1
},
"maintenance": {
"has_maintainer": 1,
"news_current": 1
},
"transparency": {
"has_source_control": 1,
"has_bug_reports_url": 1
}
}
```
</details>
> Prepare 0.2.2 release

- .github/actions/setup-cmdstan/action.yaml
- .github/workflows/main.yaml
- tests/testthat/helpers-skip.R
- tests/testthat/test-add-file-to-model-dir.R
- tests/testthat/test-check-stan-model.R
- tests/testthat/test-install-torsten.R
- tests/testthat/test-new-model.R
- tests/testthat/test-read-fit-model.R
- tests/testthat/test-stan-gq-parent.R
- tests/testthat/test-stan-summary-log.R
- tests/testthat/test-stanargs.R
- tests/testthat/test-workflow-stan-gq.R
- tests/testthat/test-workflow-stan-repr.R
- tests/testthat/test-workflow-stan.R
This PR has two changes that bring the CI time (most recent runs have been somewhere between 11 and 16 minutes) down:
* restrict the run of the `install_torsten` tests to a scheduled cron job
* cache the cmdstan installation (when there's a hit, the step goes from a bit under 2 minutes to under 10 seconds)
On top of that, there's a commit to skip tests that require cmdstan if cmdstan isn't installed.  I'll push this after the build completes for the first two commits so that we have a run with the cache in effect.
> ci: cache cmdstan install and restrict Torsten tests to cron job
